### ISSUE TITLE
ESlint Fixes

### ISSUE THREAD

**Issue by entrptaher** [vanila-io/wireflow#18]
There are many packages that requires eslint. 
Can we fix the eslint errors at once so that other commits would have their own meaning?

For example, `Remove react-komposer package` should mean it removes `react-komposer` package and nothing else. But it also have a lot of eslint fixes. 

So maybe we can focus on one PR that focuses on only ESLint related problems through all files of wireflow app.

@badis since you worked on this, what's your opinion?

**Comment by badis** [comment]
I was thinking to incrementally fix ESLint errors in a separate commit in each pull request.
Pull request: ``` remove react-komposer package ``` contains two commits: one for only changes in files related to react-komposer fixes and another commit for further ESLint enhancements. 
There was thousands of errors and warnings. now there are around 300 exist.
I was mainly fixing warnings related to: indentation, missing semi-colons and use single quotes instead of double.
What's remains is related to undefined variables, unused variables mainly in /lib folder.
Yes that would be great to fix all ESLint errors in one PR if anyone is interested, but I am still not understanding well the source code. especially in /lib folder.
