### ISSUE TITLE
Save project

### ISSUE THREAD

**Issue by NilsMinor** [vanila-io/wireflow#27]
Hi, your project is awesome!
Will it be possible in the future to store the Wireflow's I made?

**Comment by shtefcs** [comment]
Hey Nils, glad you like the Wireflow. Hope you find it useful even its buggy.

Hmm, currently I think u will be able to have automatically saved wireflows if you register. Or even without registration, it should be accessible when you access the same URL.

I would like to re-build Wireflow from scratch since we have great concept/prototype which peopel use daily. 

Tomorrow I will have a call with Adobe Funds, and see if we can get some grants for further development of Wireflow.

**Comment by NilsMinor** [comment]
Hi Stefan,
thanks for your answer, I will give it a try :)

Sounds great hope to see progress in your project as it is pretty awesome! 
Hopefully Adobe can spend some money to the project, I think they collect enough 🤑

**Comment by derwaldgeist** [comment]
Just wanted to drop by to say this is an amazing project.

**Comment by shtefcs** [comment]
> Just wanted to drop by to say this is an amazing project.

It would be even more amazing if it's built from scratch using a different stack.

I had something in mind, so if someone interested to talk and try it, hit me up on stefan@vanila.io or via Vanila Community https://community.vanila.io/users/kinderminder
